-  MSFT_ServiceResource:
    ResourceID : '[Service]bits'
    name: bits
    status: Running
    ensure: present
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0

-  MSFT_ServiceResource:
    ResourceID : '[Service]W32Time'
    name: W32Time
    status: Stopped
    ensure: present
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
    DependsOn :
      - '[Service]bits'

-  MSFT_FileDirectoryConfiguration:
    ResourceID : '[File]myfile'
    Type: File
    Contents : 'Hello world'
    ensure: present
    DestinationPath: C:\\temp\\docker\\test.txt
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
