-  MSFT_FileDirectoryConfiguration:
    ResourceID : '[File]myfile'
    Type: File
    Contents : 'Hello world'
    ensure: present
    DestinationPath: C:\\temp\\test.txt
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
