skip_commits:
  message: /updated readme.*/

os: "WMF 5"

install:
  - ps: Install-PackageProvider Nuget -ForceBootstrap -Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module Pester -Force
  - ps: Install-Module PsScriptAnalyzer -force

build: false

version: '0.1.{build}'

test_script:

# Test with native PS version
  #- ps: Invoke-Pester .\Tests\linting.ps1 (uncomment later of course)
  - ps: . .\Tests\appveyor.pester.ps1 -Test

# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize

branches:
  # whitelist
  only:
    - master
