-  nodes:
    name :
     - Nano3

   configs:
    name :
     - BasicExample

-  nodes:
    name :
     - Nano1
     - Nano2

   configs:
    name :
     - AnotherExample

    lcm:
      - autocorrect
