-  feature:
    ResourceID : '[WindowsFeature]webserver'
    name: Web-Server
    ensure: present
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0

-  feature:
    ResourceID : '[WindowsFeature]ASPnet45'
    name: Web-Asp-Net45
    ensure: $myawesomeconfig.ensure
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0

-  MSFT_xWebsite:
    ResourceID : '[xWebsite]DefaultSite'
    PhysicalPath: C:\\inetpub\\wwwroot
    state: Started
    Name: 'Default Web Site'
    ensure: present
    ModuleName : xWebAdministration
    ModuleVersion : 1.12.0.0
    DependsOn : '[WindowsFeature]webserver'

-  file:
    ResourceID : '[File]webcontents'
    Type: File
    Contents : 'Testing Complete'
    recurse : true
    ensure: present
    Attributes :
      - Archive
      - ReadOnly
    DestinationPath: C:\\inetpub\\wwwroot\\index.html
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
    DependsOn : '[xWebsite]DefaultSite'
