-  service:
    ResourceID : '[Service]bits'
    name: $myawesomeconfig.servicename
    status: Running
    ensure: $myawesomeconfig.ensure
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0

-  service:
    ResourceID : '[Service]W32Time'
    name: W32Time
    status: Stopped
    ensure: $myawesomeconfig.ensure
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
    DependsOn : '[Service]bits'

-  file:
    ResourceID : '[File]myfile'
    Type: File
    Contents : 'Hello world'
    ensure: present
    DestinationPath: C:\\temp\\awesome\\test.txt
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0
