-  xRemoteFile:
    Uri : 'https://github.com/git-for-windows/git/releases/download/v2.9.0.windows.1/Git-2.9.0-64-bit.exe'
    DestinationPath : "$($env:Temp)Git-2.9.0-64-bit.exe"
    MatchSource: $false
    ModuleName : xPsDesiredStateConfiguration

-  Package:
    Ensure : present
    Path  : "$($env:Temp)Git-2.9.0-64-bit.exe"
    Name : "Git version 2.9.0"
    ProductId : ""
    Arguments : '/VERYSILENT /NORESTART /NOCANCEL /SP- /COMPONENTS="icons,icons\quicklaunch,ext,ext\shellhere,ext\guihere,assoc,assoc_sh" /LOG'
    ModuleName : PsDesiredStateConfiguration
