-  xRemoteFile:
    Uri : 'https://nodejs.org/dist/v5.12.0/node-v5.12.0-x64.msi'
    DestinationPath : "$($env:Temp)node-v5.12.0-x64.msi"
    MatchSource: $false
    ModuleName : xPsDesiredStateConfiguration

-  Package:
    Ensure : present
    Path  : "$($env:Temp)node-v5.12.0-x64.msi"
    Name : "Node.js"
    ProductId : "CE9C30F7-140C-4A6B-95C8-8304CCBF0145"
    Arguments : '/qn ALLUSERS=1 REBOOT=ReallySuppress'
    ModuleName : PsDesiredStateConfiguration
