-  WindowsFeature:
    name: Web-Server
    ensure: present
    ModuleName : PsDesiredStateConfiguration

-  Service:
    name: bits
    status: running
    ensure: present
    ModuleName : PsDesiredStateConfiguration
