-  Feature:
    name: Web-Server
    ensure: present
    ModuleName : PsDesiredStateConfiguration

-  Service:
    name: bits
    status: stopped
    ensure: present
    ModuleName : PsDesiredStateConfiguration
