-  service:
    ResourceID : '[Service]WindowsFirewall'
    name: MPSSvc
    ensure: present
    state : Running
    StartupType : Automatic
    ModuleName : PsDesiredStateConfiguration
    ModuleVersion : 1.0

-  xDSCFirewall:
    ResourceID : '[xDSCFirewall]PublicFirewall'
    Zone : Public
    ensure: present
    ModuleName : xDSCFirewall 
    ModuleVersion : 1.0
    DependsOn : '[Service]WindowsFirewall'

-  xDSCFirewall:
    ResourceID : '[xDSCFirewall]DomainFirewall'
    Zone : Domain
    ensure: absent
    ModuleName : xDSCFirewall 
    ModuleVersion : 1.0
    DependsOn : '[Service]WindowsFirewall'

-  xDSCFirewall:
    ResourceID : '[xDSCFirewall]PrivateFirewall'
    Zone : Private
    ensure: present
    ModuleName : xDSCFirewall 
    ModuleVersion : 1.0
    DependsOn : '[Service]WindowsFirewall'

-  MSFT_xPowerShellExecutionPolicy:
    ResourceID : '[xPowerShellExecutionPolicy]ExecutionPolicy'
    ModuleName : xPowerShellExecutionPolicy
    ModuleVersion : 1.1.0.0
    ExecutionPolicy : Unrestricted
    DependsOn : '[xDSCFirewall]PrivateFirewall'
